-- Eliminar tablas
DROP TABLE CONTRATOS CASCADE CONSTRAINTS;
DROP TABLE BANDAS CASCADE CONSTRAINTS;
DROP TABLE PERSONAS CASCADE CONSTRAINTS;
DROP TABLE TITULARES CASCADE CONSTRAINTS;
DROP TABLE CURIOSIDADES CASCADE CONSTRAINTS;
DROP TABLE HERMANDADES CASCADE CONSTRAINTS;
DROP TABLE MUNICIPIOS CASCADE CONSTRAINTS;
-- Eliminar tabla temporal (inserts de hermandades)
DROP TABLE hermandades_temp CASCADE CONSTRAINTS FORCE;
DROP TABLE titulares_temp CASCADE CONSTRAINTS FORCE;
-- Eliminar paquetes
DROP PACKAGE PaqueteHermandad;
-- Eliminar secuencias
DROP SEQUENCE CONTRATOS_SEQ;
DROP SEQUENCE BANDAS_SEQ;
DROP SEQUENCE PERSONAS_SEQ;
DROP SEQUENCE TITULARES_SEQ;
DROP SEQUENCE CURIOSIDADES_SEQ;
DROP SEQUENCE HERMANDADES_SEQ;
DROP SEQUENCE MUNICIPIOS_SEQ;
-- Eliminar tipos
DROP TYPE contrato_objtyp FORCE;
DROP TYPE lista_contratos_tabletyp FORCE;
DROP TYPE persona_objtyp FORCE;
DROP TYPE lista_hermanos_tabletyp FORCE;
DROP TYPE titular_objtyp FORCE;
DROP TYPE lista_titulares_tabletyp FORCE;
DROP TYPE banda_objtyp FORCE;
DROP TYPE curiosidad_objtyp FORCE;
DROP TYPE hermandad_objtyp FORCE;
DROP TYPE lista_hermandades_tabletyp FORCE;
DROP TYPE municipio_objtyp FORCE;
DROP TYPE lista_curiosidades_tabletyp FORCE;