-- Secuencia para la PK de la tabla CONTRATOS
CREATE SEQUENCE CONTRATOS_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE
/*no se reinicia despues de llegar al maximo*/
CACHE 20;
/*se almacenan los siguientes 20 valores*/
-- Secuencia para la PK de la tabla BANDAS
CREATE SEQUENCE BANDAS_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE CACHE 20;
-- Secuencia para la PK de la tabla PERSONAS
CREATE SEQUENCE PERSONAS_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE CACHE 20;
-- Secuencia para la PK de la tabla TITULARES
CREATE SEQUENCE TITULARES_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE CACHE 20;
-- Secuencia para la PK de la tabla CURIOSIDADES
CREATE SEQUENCE CURIOSIDADES_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE CACHE 20;
-- Secuencia para la PK de la tabla HERMANDADES
CREATE SEQUENCE HERMANDADES_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE CACHE 20;
-- Secuencia para la PK de la tabla MUNICIPIOS
CREATE SEQUENCE MUNICIPIOS_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE CACHE 20;