-- Bandas de Sevilla
INSERT INTO BANDAS (nombre, tipo) VALUES ('Agrupacion Musical Ntra. Seniora de la Encarnacion', 'Agrupacion Musical');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Nuestra Seniora del Carmen de Salteras', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Golgota', 'Trio de Capilla');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Ntra. Seniora de la Victoria', 'Trio de Capilla');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Nuestra Seniora de la Victoria, Las Cigarreras', 'Cornetas y Tambores');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Nuestro Padre Jesus de la Redencion tras el senior', 'Agrupacion Musical');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Banda Jesus Nazareno de Sevilla', 'Agrupacion Musical');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Santa Ana de Dos Hermanas', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('La Sentencia de Jerez', 'Agrupacion Musical');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Las Nieves de Olivares', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Presentacion al Pueblo de Dos Hermanas', 'Cornetas y Tambores');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Rosario de Sanlucar la Mayor', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Santa Cecilia', 'Agrupacion Musical');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Las Angustias', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('La Cruz Roja', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Nuestro Padre Jesus de la Salud', 'Agrupacion Musical');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Banda de Musica de Coria del Rio', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Nuestra Seniora del Sol', 'Cornetas y Tambores');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Virgen de los Reyes', 'Agrupacion Musical');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Liceo Municipal de Moguer', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Santa Maria Magdalena de Arahal', 'Agrupacion Musical');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Banda Municipal de Mairena del Alcor', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Capilla Musical Maria Auxiliadora', 'Trio de Capilla');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Maestro Tejera', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Esencia', 'Cornetas y Tambores');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Tres Caidas de Triana', 'Cornetas y Tambores');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Nuestra Seniora de la Oliva de Salteras', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Nuestra Seniora de la Victoria', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('San Juan Evangelista de Triana', 'Cornetas y Tambores');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Virgen del Castillo de Lebrija', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Pasion de Linares', 'Agrupacion Musical');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Calvarium', 'Trio de Capilla');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Nuestra Seniora del Rosario de Cadiz', 'Cornetas y Tambores');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Santa Maria de la Esperanza', 'Cornetas y Tambores');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Nuestro Padre Jesus Nazareno de Huelva', 'Cornetas y Tambores');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Los Gitanos', 'Agrupacion Musical');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Cristo de la Sangre', 'Cornetas y Tambores');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Banda Municipal de la Puebla del Rio', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Julian Cerdan de Sanlucar de Barrameda', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Ntra. Sra. del Aguila de Alcala de Guadaira', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Banda Municipal de la Puebla del Rio', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Capilla Musical', 'Trio de Capilla');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Soledad de Cantillana', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Centuria Romana Macarena', 'Cornetas y Tambores');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Carmen de Villalba del Alcor', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Ars Sacra', 'Trio de Capilla');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Paso y Esperanza de Malaga', 'Cornetas y Tambores');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Municipal de Arahal', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('La Pasion', 'Trio de Capilla');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Nuestra Seniora del Sol', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Coral Polifonica', 'Trio de Capilla');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Banda Municipal de Sevilla', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Banda del Ejercito', 'Banda de Musica');
-- Bandas de Cadiz
INSERT INTO BANDAS (nombre, tipo) VALUES ('Polillas', 'Agrupacion Musical');
INSERT INTO BANDAS (nombre, tipo) VALUES ('La Salud', 'Agrupacion Musical');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Nuestra Padre Jesus Nazareno de San Fernando', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Santa Cruz de Almeria', 'Cornetas y Tambores');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Cristo de la Columna de Daimiel', 'Cornetas y Tambores');
INSERT INTO BANDAS (nombre, tipo) VALUES ('La Union', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Banda del Ejercito', 'Cornetas y Tambores');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Filarmonica de Conil', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Nuestra Seniora del Rosario de Arriate', 'Cornetas y Tambores');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Nuestro Padre Jesus Nazareno de Rota', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Veracruz de Utrera', 'Cornetas y Tambores');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Nuestra Seniora del Rosario del Cuervo', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Lignum Crucis', 'Trio de Capilla');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Enrique Montero de Chiclana', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Gailin de Puerto Serrano', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Virgen de la Oliva', 'Agrupacion Musical');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Nuestra Seniora de Palomares de Trebujena', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Los Gitanos de Malaga', 'Cornetas y Tambores');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Union Musical Astigitana de Ecija', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('La Humildada de Huelva', 'Cornetas y Tambores');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Sagrada Resurreccion de Chiclana', 'Agrupacion Musical');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Bollullos del Condado', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Maestro Alvarez Hidalgo', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Quinteto Julian Cerdan', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Jesus Cautivo de Estepona', 'Agrupacion Musical');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Maestro Enrique Galan de Rota', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Santa Cruz de Huelva', 'Agrupacion Musical');
INSERT INTO BANDAS (nombre, tipo) VALUES ('La Salud de Barbate', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Calvarium de Sevilla', 'Trio de Capilla');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Nuestra Seniora del Carmen de Padro del Rey', 'Banda de Musica');
INSERT INTO BANDAS (nombre, tipo) VALUES ('Ecce Mater Tua', 'Agrupacion Musical');