INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Hermandad de Pino Montano',      1982, 'Viernes de Dolores');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Hermandad de La Misión',         1949, 'Viernes de Dolores');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Hermandad de Bellavista',        1992, 'Viernes de Dolores');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Hermandad de Pasión y Muerte',   1991, 'Viernes de Dolores');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Hermandad de La Corona',         1340, 'Viernes de Dolores');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Hermandad del Divino Perdón',    1990, 'Sábado de Pasión');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Hermandad de Padre Pío',         2005, 'Sábado de Pasión');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Hermandad de los Dolores',       1994, 'Sábado de Pasión');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Hermandad de La Milagrosa',      1998, 'Sábado de Pasión');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Hermandad de San José Obrero',   1960, 'Sábado de Pasión');
/*INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'La Borriquita',                1700, 'Domingo de Ramos');*/
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Jesús Despojado',                1936, 'Domingo de Ramos');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'La Paz',                         1939, 'Domingo de Ramos');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'La Cena',                        1580, 'Domingo de Ramos');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'La Hiniesta',                    1412, 'Domingo de Ramos');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'San Roque',                      1901, 'Domingo de Ramos');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'La Estrella',                    1560, 'Domingo de Ramos');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'La Amargura',                    1893, 'Domingo de Ramos');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'El Amor',                        1508,' Domingo de Ramos');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'San Pablo',                      2005, 'Lunes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'La Redencion',                   1955, 'Lunes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Santa Genoveva',                 1956, 'Lunes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Santa Marta',                    1948, 'Lunes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'San Gonzalo',                    1942, 'Lunes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Veracruz',                       1448, 'Lunes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Las Penas',                      1875, 'Lunes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Las Aguas',                      1750, 'Lunes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'El Museo',                       1575, 'Lunes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'El Cerro',                       1944, 'Martes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Los Javieres',                   1955, 'Martes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'San Esteban',                    1926, 'Martes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Los Estudiantes',                1924, 'Martes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'San Benito',                     1554, 'Martes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'La Candelaria',                  1921, 'Martes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'El Dulce nombre',                1584, 'Martes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Santa Cruz',                     1904, 'Martes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Carmen Doloroso',                1982, 'Miércoles Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'La Sed',                         1969, 'Miércoles Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'San Bernardo',                   1748, 'Miércoles Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'El Buen Fin',                    1590, 'Miércoles Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'La Lanzada',                     1595, 'Miércoles Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'El Baratillo',                   1693, 'Miércoles Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Cristo de Burgos',               1943, 'Miércoles Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Las Siete Palabras',             1561, 'Miércoles Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Los Panaderos',                  1601, 'Miércoles Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Los Negritos',                   1393, 'Jueves Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'La Exaltación',                  1660, 'Jueves Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Las Cigarreras',                 1563, 'Jueves Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Montesión',                      1560, 'Jueves Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'La Quinta Angustia',             1500, 'Jueves Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'El Valle',                       1590, 'Jueves Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Pasión',                         1535, 'Jueves Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'El Silencio',                    1340, 'Madrugada');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'El Gran Poder',                  1431, 'Madrugada');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Macarena',                       1595, 'Madrugada');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'El Calvario',                    1571, 'Madrugada');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Esperanza de Triana',            1418, 'Madrugada');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Los Gitanos',                    1753, 'Madrugada');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'La Carretería',                  1550, 'Viernes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'La Soledad de San Buenaventura', 1847, 'Viernes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'El Cachorro',                    1689, 'Viernes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'La O',                           1566, 'Viernes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'San Isidoro',                    1605, 'Viernes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Montserrat',                     1601, 'Viernes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'La Sagrada Mortaja',             1592, 'Viernes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'El Sol',                         1932, 'Sábado Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Los Servitas',                   1696, 'Sábado Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'La Trinidad',                    1507, 'Sábado Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'Santo Entierro',                 1570, 'Sábado Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'La Soledad de San Lorenzo',      1575, 'Sábado Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (1, 'La Resurrección',                1969, 'Domingo de Resurreción');