INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Orden Tercera de Servitas',                1735, 'Viernes de Dolores');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Archicofradia de la Merced',                1626, 'Sabado de Pasión');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de la Borriquita',                1944, 'Domingo de Ramos');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de Jesús Despojado',              2007, 'Domingo de Ramos');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de la Cena',                      1963, 'Domingo de Ramos');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de las Penas',                    1977, 'Domingo de Ramos');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de Humildad y Paciencia',         1621, 'Domingo de Ramos');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de la Palma',                     1961, 'Lunes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad del Prendimiento',                1976, 'Lunes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad del Nazareno del Amor',           1951, 'Lunes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de la Vera Cruz',                 1566, 'Lunes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de Jesús Caído (Universitarios)', 1942, 'Martes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad del Ecce Homo',                   1668, 'Martes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de la Columna',                   1660, 'Martes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de la Piedad',                    1731, 'Martes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de la Sanidad',                   1946, 'Martes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de las Cigarreras',               1912, 'Miércoles Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de Sentencia (Estudiantes)',      1929, 'Miércoles Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de las Aguas',                    1944, 'Miércoles Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de la Virgen de las Angustias',   1748, 'Miércoles Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de la Oración en el Huerto',      1955, 'Jueves Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de los Afligidos',                1726, 'Jueves Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de Medinaceli',                   1938, 'Jueves Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de Jesús Nazareno',               1590, 'Jueves Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad del Perdón',                      1935, 'Madrugada');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad del Descendimiento',              1664, 'Viernes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de la Expiración',                1944, 'Viernes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad de las Siete Palabras',           1944, 'Viernes Santo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Congregación Ecce Mater Tua',               1953, 'Sábado Santoo');
INSERT INTO Hermandad (ciudad, nombre, año_fundacion, dia_salida) VALUES (2, 'Hermandad del Santo Entierro',              1601, 'Sábado Santo');
